### PR TITLE
Resolved the conflict between asynchronous Reducer and Pipeline parallelism 

### PR DESCRIPTION
**Pull request by CraneQinghe**
The current pipeline parallelism generates multiple backward codes within gencode.py. If asynchronous gradient communication is used, the post_grad_hook in reducer.py will perform gradient synchronization during each backward pass, triggering errors. I have created a singleton class accum_Manager in nnscaler/utils.py to manage gradient accumulation and gradient synchronization communication. Asynchronous gradient communication only occurs when the number of backward passes reaches the specified gradient accumulation steps.

In nnscaler/cli/trainer.py at line 791, this instance is created, and the set_nsteps function is called to specify the gradient accumulation steps. Additionally, accum_manager.reset() is added at line 803 to reset the accumulation step count for each iteration. In runtime/executor.py at line 194, the step() function is called to increment the backward pass count.

### CODE REVIEW

**Comment by zyeric** [comment]
Thanks for your contribution :)
1. could you explain why `post_grad_hook` will be called multiple times in `_train_step` for pipeline parallelism? In my understanding, the reducer.sync_grads() is called at the end of `_train_step`
2. please add a test to make the expected behavior clearer, you can refer to https://github.com/microsoft/nnscaler/blob/main/tests/parallel_module/test_e2e_detach_loss.py as an example

**Comment by CraneQinghe** [comment]
Sorry for the inaccurate expression I used yesterday. The issue occurs when "pipeline parallelism is used simultaneously, along with setting the gradient accumulation steps (i.e., num_microbatches) greater than 1, and asynchronous gradient communication is enabled." In this case, the gencode.py file’s _train_step will call the forward pass 4 times and the backward pass 4 times, as shown in the figure below:
pipeline_parallel_image_2_zh

Although `reducer.sync_grads()` is called at the end of `_train_step`, with asynchronous gradient updates, gradient communication happens within the `post_grad_hook`. Since the `post_grad_hook` function is registered at the operator level, each time a backward pass is called within `_train_step`, the `post_grad_hook` function is triggered for every operator. The `_async_param_cnt` within this function is incremented. Since `len(self._params)` is always equal to 1, a RuntimeError is raised:
```python
     if self._async_param_cnt > len(self._params):
                    raise RuntimeError(
                        "Detected gradient accumulation with asynchronous Reducer. "
                        "Users should run with `nnscaler.accum_mode` to manage gradient synchronization.")
```
If we comment out this if condition, asynchronous gradient communication will occur at every backward pass. This deviates from the intended behavior. Therefore, we need to add a counter for each backward pass, and only when the gradient accumulation steps are reached should the asynchronous gradient communication in `post_grad_hook` be triggered.

**Comment by zyeric** [comment]
@CraneQinghe  Thanks for your explanation in details and I understand the problem.
Agree with weijiang, the root cause is we should control the gradient accumulation carefully inside the `_train_step` function. In the pipeline example you attached, we can enable it only at backward-3 at each stage.

**Comment by zyeric** [comment]
Personally I encourage you to fix it at the gencode side since it helps to understand the compiling process that nnScaler adopts. But it is OK to leave it to us.

**Comment by CraneQinghe** [comment]
@zyeric Thank you for your suggestions. I will take a closer look at the gencode generation part when I have time later. However, our focus is not on this aspect right now, so I don’t have time to make changes for the moment. I’ll leave it to you experts to handle it. ^_^

**Comment by zyeric** [comment]
Many thanks, we will add this bug to our TODO list.

**Pull request closed without merging**
